#### general settings
name: tmp
use_tb_logger: false #true
model: VideoSR_base
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: Adobe_test_3
    mode: Adobe_test_3 # Adobe & Adobe_a
    #name: Gopro_test_a
    #mode: Gopro_test_a
    interval_list: [1]
    random_reverse: false #false
    border_mode: false
    #dataroot_GT: /work/abcd233746pc/test
    #dataroot_LQ: /work/abcd233746pc/test_4
    #dataroot_GT: /work/abcd233746pc/frame_without_split/test
    #dataroot_LQ: /work/abcd233746pc/frame_without_split_4/test
    dataroot_GT: /home/abcd233746pc/Vid4/test_pair/HR
    dataroot_LQ: /home/abcd233746pc/Vid4/test_pair/LR
    cache_keys: data/Vimeo7_train_keys.pkl

    N_frames: 7
    use_shuffle: false
    n_workers: 3  # per GPU
    batch_size: 1
    GT_size: 1280
    LQ_size: 32
    use_flip: false
    use_rot: false
    color: RGB
    sample_num: 7
    ref_num: 2

#### network structures
network_G:
  which_model_G: Ours # LunaTokis & LIIF
  nf: 64
  nframes: 7
  groups: 8
  front_RBs: 5
  mid_RBs: 0
  back_RBs: 40
  HR_in: false

  setting: 5

#### path
path:
  

  pretrain_model_G: ./saved_checkpoints/best.pth

  strict_load: true #true #
  resume_state: ~
  models: ./saved_checkpoints/
  training_state: ./saved_checkpoints/
  root: ./

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 0.0
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 1522 #4406 # 83 # 1522
  warmup_iter: -1 #4000  # -1: no warm up
  T_period: [150000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 1
  save_checkpoint_freq: !!float 4e3
